apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:   # for pod definition
    metadata:
      name: redis-pod
      labels:
        app: redis-pod
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    app: redis-pod
  ports:
  - port: 6379
    targetPort: 6379
