apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:   # for pod definition
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: voting
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80