apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pod
  template:   # for pod definition
    metadata:
      labels:
        app: postgres-pod
    spec:
      containers:
      - name: database
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          # pointer to the configuration of HOW we want the mount to be implemented
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres-pod
  ports:
  - port: 5432
    targetPort: 5432
